version: '3.8'

services:
  DB:
    image: mysql:8.0.28
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'svconnect'
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
